// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsLetterService.Infrastructure.Persistence;

#nullable disable

namespace NewsLetterService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NewsLetterServiceDbContext))]
    partial class NewsLetterServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewsLetterService.Domain.Entities.NewsLetterHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Act")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfAct")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewsLetterId")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("NewsLetterId", "PersonnelId", "Act")
                        .IsUnique();

                    b.ToTable("NewsLetterHistory", (string)null);
                });

            modelBuilder.Entity("NewsLetterService.Domain.Entities.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Personnel", (string)null);
                });

            modelBuilder.Entity("NewsLetterService.Domain.Entities.NewsLetterHistory", b =>
                {
                    b.HasOne("NewsLetterService.Domain.Entities.Personnel", "Personnel")
                        .WithMany("NewsLetterHistories")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("NewsLetterService.Domain.Entities.Personnel", b =>
                {
                    b.Navigation("NewsLetterHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
